# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ece": "metrics.ipynb",
         "ece_v2": "metrics.ipynb",
         "ece_v3": "metrics.ipynb",
         "ece_v4": "metrics.ipynb",
         "class_wise_ece": "metrics.ipynb",
         "ridge_diagram": "plots.ipynb",
         "ridge_reliability_diagram": "plots.ipynb",
         "class_wise_ridge_reliability_diagram": "plots.ipynb",
         "bar_diagram": "plots.ipynb",
         "confidence_reliability_diagram": "plots.ipynb",
         "class_wise_confidence_reliability_diagram": "plots.ipynb",
         "freedman_diaconis": "utils.ipynb",
         "get_bin_indices": "utils.ipynb",
         "binning": "utils.ipynb"}

modules = ["metrics.py",
           "plots.py",
           "utils.py"]

doc_url = "https://MaximLippeveld.github.io/ridgereliability/"

git_url = "https://github.com/MaximLippeveld/ridgereliability/tree/master/"

def custom_doc_links(name): return None
