# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://MaximLippeveld.github.io/ridge_reliability/"

git_url = "https://github.com/MaximLippeveld/ridge_reliability/tree/master/"

def custom_doc_links(name): return None
