# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_beta_parameters": "beta_utils.ipynb",
         "convolve_betas_fft": "beta_utils.ipynb",
         "convolve_betas": "beta_utils.ipynb",
         "balanced_accuracy_expected": "beta_utils.ipynb",
         "beta_sum_pdf": "beta_utils.ipynb",
         "beta_avg_pdf": "beta_utils.ipynb",
         "beta_sum_cdf": "beta_utils.ipynb",
         "beta_avg_cdf": "beta_utils.ipynb",
         "beta_avg_inv_cdf": "beta_utils.ipynb",
         "recall": "beta_utils.ipynb",
         "precision": "beta_utils.ipynb",
         "mpba_score": "beta_utils.ipynb",
         "micro_f1_score": "beta_utils.ipynb",
         "peace": "metrics.ipynb",
         "ece": "metrics.ipynb",
         "ece_v2": "metrics.ipynb",
         "class_wise_error": "metrics.ipynb",
         "clipped_cm": "plots.ipynb",
         "river_diagram": "plots.ipynb",
         "river_reliability_diagram": "plots.ipynb",
         "class_wise_river_reliability_diagram": "plots.ipynb",
         "bar_diagram": "plots.ipynb",
         "confidence_reliability_diagram": "plots.ipynb",
         "class_wise_confidence_reliability_diagram": "plots.ipynb",
         "get_bin_indices": "utils.ipynb",
         "binning": "utils.ipynb"}

modules = ["beta.py",
           "metrics.py",
           "plots.py",
           "utils.py"]

doc_url = "https://MaximLippeveld.github.io/riverreliability/"

git_url = "https://github.com/MaximLippeveld/riverreliability/tree/master/"

def custom_doc_links(name): return None
